name: Build OpenWrt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils python3-pyelftools python3-setuptools rsync unzip \
            zlib1g-dev file wget pip python3-pip

      - name: Clone OpenWrt
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../.config .config
          make defconfig

      - name: Build firmware
        run: |
          cd openwrt
          make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/

