name: 编译 LEDE 固件（小米路由器 3，MT7620A）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译小米路由器 3 固件
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 设置编译环境
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y coreutils build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3 python3-all rsync unzip zlib1g-dev file wget
          sudo ln -s /usr/bin/sha256sum /usr/bin/sha256

      - name: 修复 python distutils 问题
        run: |
          python3 -m ensurepip --upgrade || echo "ensurepip 已安装，无需处理"

      - name: 克隆 LEDE 源码
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 准备 .config 配置文件
        run: |
          cd lede
          cat > .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7620=y
          CONFIG_TARGET_ramips_mt7620_DEVICE_xiaomi_miwifi-r3=y
        
          CONFIG_BUSYBOX_CUSTOM=y
          CONFIG_LIBCURL_USE_OPENSSL=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_libpthread=y
          CONFIG_PACKAGE_librt=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_DROPBEAR_ECC=y
          CONFIG_STRIP_KERNEL_EXPORTS=y

  # 网络核心模块（sing-box、passwall2、naiveproxy 等代理软件依赖）
         
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-nf-nat=y
          CONFIG_PACKAGE_kmod-ipt-nat=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-ipt-conntrack=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-nf-reject=y
          CONFIG_PACKAGE_kmod-nf-raw=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y

  # 流控调度模块
          CONFIG_PACKAGE_kmod-sched=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sched-cake=y
        
          # 加密相关内核模块
          CONFIG_PACKAGE_kmod-crypto-aead=y
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-crypto-null=y
          CONFIG_PACKAGE_kmod-crypto-user=y

  # USB 支持（仅限 U 盘）
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-nls-base=y

  # Cloudflare DDNS
          CONFIG_PACKAGE_ddns-scripts=y
          CONFIG_PACKAGE_ddns-scripts-cloudflare=y

  # 禁用 IPv6 以节省空间
          CONFIG_IPV6=n
EOF
          make defconfig

      - name: 检查目标配置
        run: |
          cd lede
          echo "=== 检查 Xiaomi 设备支持 ==="
          grep -r "xiaomi" target/linux/ramips/image/ || echo "未找到 Xiaomi 设备支持"
          echo "=== 尝试编译通用 MT7620 固件 ==="
          echo "注意：小米路由器 3 (MT7620A) 可能不被官方支持"
          echo "将生成通用 MT7620 固件，兼容性未知"

      - name: 开始编译
        run: |
          cd lede
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: Xiaomi-R3-Firmware
          path: lede/bin/targets/ramips/mt7620/

      - name: 上传内核模块和软件包
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Packages
          path: lede/bin/packages/mipsel_24kc/

