name: Build LEDE for Xiaomi R3 (MT7620A)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LEDE for Xiaomi Mi Router 3
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up environment
  run: |
    sudo apt update
    sudo apt install -y software-properties-common
    sudo add-apt-repository universe
    sudo apt update
    sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
      gettext git libncurses-dev libssl-dev python3.11-distutils rsync unzip zlib1g-dev file wget


      - name: Clone LEDE source
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare .config
        run: |
          cd lede
          cat > .config <<EOF
          CONFIG_MODULES=y
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7620=y
          CONFIG_TARGET_ramips_mt7620_DEVICE_xiaomi_mir3=y
          CONFIG_BUSYBOX_CUSTOM=y
          CONFIG_LIBCURL_USE_OPENSSL=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_libpthread=y
          CONFIG_PACKAGE_librt=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_DROPBEAR_ECC=y
          CONFIG_STRIP_KERNEL_EXPORTS=y

          # Common kernel modules for proxy/networking features
          CONFIG_PACKAGE_kmod-nf-nat=y
          CONFIG_PACKAGE_kmod-ipt-nat=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-nf-reject=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-nf-raw=y
          CONFIG_PACKAGE_kmod-slhc=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-conntrack=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          CONFIG_PACKAGE_kmod-nf-nathelper=y
          CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
          CONFIG_PACKAGE_kmod-ipt-nathelper=y
          CONFIG_PACKAGE_kmod-ipt-nathelper-extra=y
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sched=y
          CONFIG_PACKAGE_kmod-sched-cake=y
          CONFIG_PACKAGE_kmod-crypto-aead=y
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-crypto-null=y
          CONFIG_PACKAGE_kmod-crypto-user=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-nls-base=y

          # Disable IPv6 to save space
          CONFIG_IPV6=n
          EOF
          make defconfig

      - name: Start compiling
        run: |
          cd lede
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: Create package index
        run: |
          cd lede/bin/packages/mipsel_24kc
          sh -c '../../../scripts/ipkg-make-index.sh . > Packages.tmp'
          mv Packages.tmp Packages
          gzip -9c Packages > Packages.gz || true

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: Xiaomi-R3-Firmware
          path: lede/bin/targets/ramips/mt7620/

      - name: Upload kernel modules & packages
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Packages
          path: lede/bin/packages/mipsel_24kc/
