name: Build OpenWrt for Newifi D2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-distutils python3-pyelftools \
            unzip wget zlib1g-dev python3-setuptools rsync subversion

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom config
        run: cp config/NewifiD2.config openwrt/.config

      - name: Build OpenWrt
        run: |
          cd openwrt
          make defconfig
          make download -j8 || true
          make -j$(nproc)

      - name: Upload firmware and ipk packages
        uses: actions/upload-artifact@v4
        with:
          name: newifi-d2-firmware-and-ipks
          path: |
            openwrt/bin/targets/ramips/mt7621/
            openwrt/bin/packages/ramips/mt7621/
