name: Build OpenWrt for Xiaomi 4C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-distutils python3-pyelftools \
            unzip wget zlib1g-dev python3-setuptools rsync subversion

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy Custom Config
        run: |
          cp .config openwrt/.config

      - name: Build
        run: |
          cd openwrt
          make defconfig
          make download -j8 || true
          make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: Xiaomi-4C-Firmware
          path: openwrt/bin/targets/
