name: 编译 LEDE 固件（小米路由器 3，MT7620A）
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译小米路由器 3 固件
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
      - name: 设置编译环境
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y coreutils build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3 python3-all rsync unzip zlib1g-dev file wget
          sudo ln -s /usr/bin/sha256sum /usr/bin/sha256
      - name: 修复 python distutils 问题
        run: |
          python3 -m ensurepip --upgrade || echo "ensurepip 已安装，无需处理"
      - name: 克隆 LEDE 源码
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 准备 .config 配置文件
        run: |
          cd lede
          cat > .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7620=y
          CONFIG_TARGET_ramips_mt7620_DEVICE_xiaomi_miwifi-r3=y
          
          # 基础系统优化
          CONFIG_BUSYBOX_CUSTOM=y
          CONFIG_LIBCURL_USE_OPENSSL=y
          CONFIG_DROPBEAR_ECC=y
          CONFIG_STRIP_KERNEL_EXPORTS=y
          CONFIG_USE_MKLIBS=y
          CONFIG_TARGET_OPTIMIZATION="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc"
          
          # 最小化 LuCI 界面
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          
          # 禁用默认的大型软件包
          CONFIG_PACKAGE_wpad-basic-wolfssl=n
          CONFIG_PACKAGE_wpad-basic-openssl=n
          CONFIG_PACKAGE_wpad-basic-mbedtls=n
          CONFIG_PACKAGE_wpad-basic=n
          CONFIG_PACKAGE_wpad-mini=y
          CONFIG_PACKAGE_hostapd-common=n
          CONFIG_PACKAGE_wireless-regdb=n
          
          # 禁用不必要的内核功能
          CONFIG_PACKAGE_kmod-usb-ohci=n
          CONFIG_PACKAGE_kmod-usb-uhci=n
          CONFIG_PACKAGE_kmod-usb3=n
          CONFIG_PACKAGE_kmod-ath=n
          CONFIG_PACKAGE_kmod-ath9k=n
          CONFIG_PACKAGE_kmod-ath9k-common=n
          CONFIG_PACKAGE_kmod-ath9k-htc=n
          CONFIG_PACKAGE_kmod-cfg80211=n
          CONFIG_PACKAGE_kmod-mac80211=n
          
          # 禁用多媒体和音频支持
          CONFIG_PACKAGE_kmod-sound-core=n
          CONFIG_PACKAGE_kmod-sound-hda-core=n
          CONFIG_PACKAGE_kmod-video-core=n
          CONFIG_PACKAGE_kmod-video-videobuf2=n
          
          # 禁用打印机支持
          CONFIG_PACKAGE_kmod-usb-printer=n
          CONFIG_PACKAGE_kmod-lp=n
          
          # 禁用蓝牙支持
          CONFIG_PACKAGE_kmod-bluetooth=n
          CONFIG_PACKAGE_kmod-hid=n
          
          # 禁用不必要的网络协议
          CONFIG_PACKAGE_kmod-ppp=n
          CONFIG_PACKAGE_kmod-pppoe=n
          CONFIG_PACKAGE_kmod-pppox=n
          CONFIG_PACKAGE_kmod-l2tp=n
          CONFIG_PACKAGE_kmod-pptp=n
          
          # 必需的基础库（最小化）
          CONFIG_PACKAGE_libpthread=y
          CONFIG_PACKAGE_librt=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libatomic=y
          
          # 禁用常见的大型软件包
          CONFIG_PACKAGE_luci-app-adbyby-plus=n
          CONFIG_PACKAGE_luci-app-accesscontrol=n
          CONFIG_PACKAGE_luci-app-arpbind=n
          CONFIG_PACKAGE_luci-app-autoreboot=n
          CONFIG_PACKAGE_luci-app-ddns=n
          CONFIG_PACKAGE_luci-app-filetransfer=n
          CONFIG_PACKAGE_luci-app-firewall=n
          CONFIG_PACKAGE_luci-app-flowoffload=n
          CONFIG_PACKAGE_luci-app-frpc=n
          CONFIG_PACKAGE_luci-app-guest-wifi=n
          CONFIG_PACKAGE_luci-app-ipsec-vpnd=n
          CONFIG_PACKAGE_luci-app-nlbwmon=n
          CONFIG_PACKAGE_luci-app-ramfree=n
          CONFIG_PACKAGE_luci-app-sfe=n
          CONFIG_PACKAGE_luci-app-ssr-plus=n
          CONFIG_PACKAGE_luci-app-turboacc=n
          CONFIG_PACKAGE_luci-app-unblockmusic=n
          CONFIG_PACKAGE_luci-app-upnp=n
          CONFIG_PACKAGE_luci-app-vsftpd=n
          CONFIG_PACKAGE_luci-app-wol=n
          CONFIG_PACKAGE_luci-app-xlnetacc=n
          CONFIG_PACKAGE_luci-app-zerotier=n
          
          # 禁用默认工具包
          CONFIG_PACKAGE_automount=n
          CONFIG_PACKAGE_autosamba=n
          CONFIG_PACKAGE_defaultroute=n
          CONFIG_PACKAGE_etherwake=n
          CONFIG_PACKAGE_htop=n
          CONFIG_PACKAGE_iperf3=n
          CONFIG_PACKAGE_coremark=n
          CONFIG_PACKAGE_wget-ssl=n
          
          # 禁用多余的内核模块
          CONFIG_PACKAGE_kmod-fs-exfat=n
          CONFIG_PACKAGE_kmod-fs-ext4=n
          CONFIG_PACKAGE_kmod-fs-ntfs=n
          CONFIG_PACKAGE_kmod-fs-vfat=n
          CONFIG_PACKAGE_kmod-nls-cp437=n
          CONFIG_PACKAGE_kmod-nls-iso8859-1=n
          CONFIG_PACKAGE_kmod-nls-utf8=n
          
          # 网络核心模块（sing-box、passwall2、naiveproxy 等代理软件依赖）
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-nf-nat=y
          CONFIG_PACKAGE_kmod-ipt-nat=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-ipt-conntrack=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-nf-reject=y
          CONFIG_PACKAGE_kmod-nf-raw=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          
          # eBPF 支持（部分新版代理软件需要）
          CONFIG_PACKAGE_kmod-bpf=y
          
          # Netfilter 扩展模块
          CONFIG_PACKAGE_kmod-nf-flow=y
          CONFIG_PACKAGE_kmod-nf-log=y
          CONFIG_PACKAGE_kmod-nf-socket=y
          CONFIG_PACKAGE_kmod-nfnetlink=y
          CONFIG_PACKAGE_kmod-nfnetlink-log=y
          CONFIG_PACKAGE_kmod-nfnetlink-queue=y
          
          # IPTables 扩展模块（透明代理必需）  
          CONFIG_PACKAGE_kmod-ipt-filter=y
          CONFIG_PACKAGE_kmod-ipt-iprange=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          CONFIG_PACKAGE_kmod-ipt-hashlimit=y
          CONFIG_PACKAGE_kmod-ipt-fullconenat=y
          CONFIG_PACKAGE_kmod-ipt-socket=y
          CONFIG_PACKAGE_kmod-ipt-account=y
          
          # 网络层模块
          CONFIG_PACKAGE_kmod-nf-nathelper=y
          CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
          CONFIG_PACKAGE_kmod-ip-mroute=y
          CONFIG_PACKAGE_kmod-ip-tunnel=y
          CONFIG_PACKAGE_kmod-ipip=y
          CONFIG_PACKAGE_kmod-gre=y
          
          # UDP/TCP 优化模块
          CONFIG_PACKAGE_kmod-tcp-bbr=y
          CONFIG_PACKAGE_kmod-udptunnel4=y
          CONFIG_PACKAGE_kmod-udptunnel6=y
          
          # 流控调度模块
          CONFIG_PACKAGE_kmod-sched=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sched-cake=y
          
          # 加密相关内核模块（代理协议加密支持）
          CONFIG_PACKAGE_kmod-crypto-aead=y
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-crypto-null=y
          CONFIG_PACKAGE_kmod-crypto-user=y
          CONFIG_PACKAGE_kmod-crypto-aes=y
          CONFIG_PACKAGE_kmod-crypto-arc4=y
          CONFIG_PACKAGE_kmod-crypto-authenc=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-ccm=y
          CONFIG_PACKAGE_kmod-crypto-cmac=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-crypto-ctr=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-ecb=y
          CONFIG_PACKAGE_kmod-crypto-gcm=y
          CONFIG_PACKAGE_kmod-crypto-gf128=y
          CONFIG_PACKAGE_kmod-crypto-ghash=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-iv=y
          CONFIG_PACKAGE_kmod-crypto-manager=y
          CONFIG_PACKAGE_kmod-crypto-md4=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-rng=y
          CONFIG_PACKAGE_kmod-crypto-seqiv=y
          CONFIG_PACKAGE_kmod-crypto-sha1=y
          CONFIG_PACKAGE_kmod-crypto-sha256=y
          CONFIG_PACKAGE_kmod-crypto-sha512=y
          CONFIG_PACKAGE_kmod-crypto-wq=y
          
          # USB 支持（仅限 U 盘）
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-nls-base=y
          
          # 代理软件常用依赖包
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          CONFIG_PACKAGE_iptables-mod-extra=y
          CONFIG_PACKAGE_iptables-mod-iprange=y
          CONFIG_PACKAGE_iptables-mod-socket=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_ip-full=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_libopenssl=y
          CONFIG_PACKAGE_zlib=y
          CONFIG_PACKAGE_libpcre=y
          CONFIG_PACKAGE_dnsmasq-full=y
          # 移除默认 dnsmasq 以使用 dnsmasq-full
          CONFIG_PACKAGE_dnsmasq=n
          
          # Cloudflare DDNS
          CONFIG_PACKAGE_ddns-scripts=y
          CONFIG_PACKAGE_ddns-scripts-cloudflare=y
          
          # 禁用 IPv6 以节省空间
          CONFIG_IPV6=n
          EOF
          make defconfig
      - name: 检查目标配置
        run: |
          cd lede
          echo "=== 检查 Xiaomi 设备支持 ==="
          grep -r "xiaomi" target/linux/ramips/image/ || echo "未找到 Xiaomi 设备支持"
          echo "=== 尝试编译通用 MT7620 固件 ==="
          echo "注意：小米路由器 3 (MT7620A) 可能不被官方支持"
          echo "将生成通用 MT7620 固件，兼容性未知"
          echo "=== 配置文件分析 ==="
          grep "=y" .config | wc -l
          echo "已启用的配置项数量"
      - name: 开始编译
        run: |
          cd lede
          make -j$(nproc) download V=s
          make -j$(nproc) V=s
      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: Xiaomi-R3-Firmware
          path: lede/bin/targets/ramips/mt7620/
      - name: 上传内核模块和软件包
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Packages
          path: lede/bin/packages/mipsel_24kc/
